//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalterAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string StaffNumber { get; set; }
        public string FirstNamePreferred { get; set; }
        public string LastNamePreferred { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OfficeID { get; set; }
        public string Title { get; set; }
        public string Password { get; set; }
        public string DepartmentID { get; set; }
        public string WorkPhone { get; set; }
        public string ActiveStatus { get; set; }
        public string EmployeeType { get; set; }
        public string FinancialResponsibility { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string TitleCode { get; set; }
        public Nullable<System.DateTime> LastHireDate { get; set; }
        public string RecID { get; set; }
        public string PhotoExists { get; set; }
        public string CellPhone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string HomePhone { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyPhone { get; set; }
        public string YRStaffNumber { get; set; }
        public string StaffNumberSupervisor { get; set; }
        public Nullable<short> CountHRIS { get; set; }
        public string Email { get; set; }
        public string EmailHost { get; set; }
        public string Division { get; set; }
        public string StaffNumberSupervisor2 { get; set; }
        public bool IsKnowledgeLeader { get; set; }
        public bool IsWiseAss { get; set; }
        public string UserNameTemp { get; set; }
        public string HomeFax { get; set; }
        public Nullable<bool> ShowHomePhone { get; set; }
        public Nullable<bool> ShowHomeFax { get; set; }
        public Nullable<bool> ShowCellPhone { get; set; }
        public string Address3 { get; set; }
        public string EmergencyRelationship { get; set; }
        public string SSNumber { get; set; }
        public string FullNameCalc { get; set; }
        public string JobClassID { get; set; }
        public bool IsKnowledgeFacilitator { get; set; }
        public string SearchName { get; set; }
        public int EmployeeID { get; set; }
        public string SearchText { get; set; }
        public string FirstNamePreferredUnicode { get; set; }
        public string LastNamePreferredUnicode { get; set; }
        public byte SearchFactor { get; set; }
        public string MiddleName { get; set; }
        public string MiddleNamePreferred { get; set; }
        public string MiddleNamePreferredUnicode { get; set; }
        public string EmergencyName2 { get; set; }
        public string EmergencyRelationship2 { get; set; }
        public string EmergencyPhone2 { get; set; }
        public string EmailHome { get; set; }
        public Nullable<bool> ShowEmailHome { get; set; }
        public Nullable<bool> ShowBirthday { get; set; }
        public byte[] EmployeeTimestamp { get; set; }
        public Nullable<System.DateTime> LastSeparationDate { get; set; }
        public string IsOnLeave { get; set; }
        public Nullable<System.DateTime> BirthdateDummyYear { get; set; }
        public string OfficeIDAdditional { get; set; }
        public string ExternalTitle { get; set; }
        public Nullable<bool> ShowCellPhoneBusinessCard { get; set; }
        public string OfficeID2 { get; set; }
        public Nullable<System.DateTime> ManagerLastRemindedAnniversary { get; set; }
        public bool EmployeeSentEmbark2MonthReminder { get; set; }
        public bool ShowAsNewEmployee { get; set; }
        public Nullable<System.DateTime> LastHireDateOverride { get; set; }
        public Nullable<float> HoursPerWeek { get; set; }
        public Nullable<byte> TempEntitlement { get; set; }
        public string Department { get; set; }
    }
}
