//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalterAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public string OfficeID { get; set; }
        public string Office1 { get; set; }
        public string ParentOfficeID { get; set; }
        public string Region { get; set; }
        public string OfficeCode { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string MainPhone { get; set; }
        public string MainFax { get; set; }
        public string OfficeNotes { get; set; }
        public string WeatherURL { get; set; }
        public bool ActiveFlag { get; set; }
        public string EmailHost { get; set; }
        public string LocationID { get; set; }
        public string LocationIDWindows { get; set; }
        public Nullable<short> StandardBias { get; set; }
        public Nullable<short> CurrencyID { get; set; }
        public bool FinancialResponsibilityFlag { get; set; }
        public bool IsPhysical { get; set; }
        public Nullable<float> FTEHours { get; set; }
        public Nullable<bool> CCEnabled { get; set; }
        public short EmployeeCount { get; set; }
        public string OfficeNameShort { get; set; }
        public Nullable<short> CountryID { get; set; }
        public string Domain { get; set; }
        public bool DomainEmail { get; set; }
        public bool DomainFileServers { get; set; }
        public string LanguageIDDefault { get; set; }
        public bool IsOracle { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string MapURLOverride { get; set; }
        public bool IsArchived { get; set; }
        public string EmailAddressAll { get; set; }
        public bool UseNewMeetingRooms { get; set; }
        public Nullable<float> Latitude { get; set; }
        public Nullable<float> Longitude { get; set; }
        public Nullable<byte> MeetingRoomStartHour { get; set; }
        public string MicrositeURL { get; set; }
        public string MapURL { get; set; }
        public string MapURLMobile { get; set; }
        public string HRISUpdateEmail { get; set; }
        public string PIFNewCompanyEmail { get; set; }
        public bool UseOfficeMailingList { get; set; }
        public bool IsNotes { get; set; }
        public string WebmailURL { get; set; }
        public bool UsePasswordForm { get; set; }
        public Nullable<byte> SortOrderCC { get; set; }
        public bool MeetingRoomsFoodJobNumberRequired { get; set; }
        public string WPPRegion { get; set; }
        public Nullable<System.DateTime> CoffeeLastBrewed { get; set; }
        public Nullable<byte> CoffeeStatus { get; set; }
        public Nullable<int> CoffeeLastBrewedByPerson { get; set; }
        public string CartesisCode { get; set; }
        public string LandorComURL { get; set; }
        public Nullable<decimal> WorkingHoursInDay { get; set; }
        public Nullable<byte> DefaultEntitlementDays { get; set; }
    }
}
